
[light_sources]
	entities = true
	self = true
	block_entities = true
	water_sensitive_check = true

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				player = true
				bat = true
				skeleton = true
				slime = true
				enderman = true
				spider = true
				item = true
				creeper = true
				axolotl = true
				zombie = true
				zombie_villager = true
				chicken = true
				cow = true
				bee = true
				glow_squid = true
				squid = true
				pig = true
				sheep = true
				tropical_fish = true
				cat = true
				iron_golem = true
				villager = true

