
[light_sources]
	entities = true
	self = true
	block_entities = true
	water_sensitive_check = true

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				player = true
				bee = true
				pig = true
				sheep = true
				cow = true
				wolf = true
				item = true
				squid = true
				zombie = true
				glow_squid = true
				skeleton = true
				bat = true
				creeper = true
				cod = true
				spider = true
				enderman = true
				salmon = true
				axolotl = true
				drowned = true
				witch = true
				dolphin = true

